WorkWithKOTE/Controllers/BuyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity.Validation;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;
using System.Data.Entity;
using WorkWithKOTE.Models;
using System.Security.Cryptography;
using System.Text;
using Newtonsoft.Json;
using DotNetOpenAuth.AspNet;
using Microsoft.Web.WebPages.OAuth;
namespace WorkWithKOTE.Controllers
{

    public class BuyController : Controller
    {
        //
        // GET: /Buy/
        //  TourContext db = new TourContext();
        UsersContext db = new UsersContext();
        public ActionResult Index(int id)
        {
            var valuta = db.Curseds.Find(1);
            ViewBag.valutaUsd = valuta.USD;
            ViewBag.valutaEuro = valuta.Evro;
            Trip data = new Trip();
            Tour tour = db.Tour.Find(id);
            if (tour != null)
            {
                data.TourId = id;
                if (tour.AukcionPrice != null)
                {
                    data.TourPrice = tour.AukcionPrice;
                    ViewBag.TourPrices = tour.AukcionPrice;
                    data.Valuta = tour.Valuta;
                }
                else
                {
                    ViewBag.TourPrices = tour.Cost;
                    data.TourPrice = tour.Cost;
                    data.Valuta = tour.Valuta;
                }
                ViewBag.DateTourId = new SelectList(db.DateTours.Where(m => m.TourId == id)
                .AsEnumerable()
                .Select(m => new
                {
                    Date = m.FirstDate.ToString("dd.MM.yyyy"),
                    ID = m.DateTourId
                }), "ID", "Date");
                data.AmtPeople = 1;
                if (Request.IsAuthenticated)
                {
                    int userID = WebSecurity.GetUserId(User.Identity.Name);
                    var userprofile = db.UserProfiles.Find(userID);
                    ViewBag.UsersBonus = userprofile.Bonus;
                    data.email = userprofile.Email;
                    data.BirthDay = userprofile.Birthday;
                    data.Citizenship = userprofile.Nationality;
                    data.Name = userprofile.RuFirstName;
                    data.Surname = userprofile.RuSecondName;
                    data.FatherName = userprofile.RuThirdName;
                    data.mobile = userprofile.Mobile;
                    data.Pasport = userprofile.PasportData;
                    data.BonusPay = tour.BonusPay;
                }
                ViewBag.TitleOf = tour.NameTour;
            }
            return View(data);
        }
        [HttpPost]
        public ActionResult Index(int id, Trip model, string DateTourId, int[] Item)
        {
            var selectedDop = new List<SelectedDopUslug>();
            var tour = db.Tour.Find(id);
            var currency = db.Curseds.Find(1);
            decimal Price = 0;
            if (tour.AukcionPrice != null)
            {
                if (tour.Valuta == "EUR")
                    Price = tour.AukcionPrice.Value * currency.Evro;
                else if (tour.Valuta == "USD")
                    Price = tour.AukcionPrice.Value * currency.USD;
                else
                    Price = tour.AukcionPrice.Value;
            }
            else
            {
                if (tour.Valuta == "EUR")
                    Price = tour.Cost.Value * currency.Evro;
                else if (tour.Valuta == "USD")
                    Price = tour.Cost.Value * currency.USD;
                else
                    Price = tour.Cost.Value;
            }
            if (Item != null)
                for (int i = 0; i < Item.Length; i++)
                {
                    var DopUslug = db.DopUslugs.Find(Item[i]);
                    selectedDop.Add(new SelectedDopUslug { SelectedDopUslugName = DopUslug.Name, SelectedDopPrice = DopUslug.Price });
                    if (tour.Valuta == "EUR")
                        Price = Price + DopUslug.Price * currency.Evro;
                    if (tour.Valuta == "USD")
                        Price = Price + DopUslug.Price * currency.USD;
                    if (tour.Valuta == "UAH")
                        Price = Price + DopUslug.Price;
                }
            model.SelectedDopUslug = new List<SelectedDopUslug>();
            foreach (var item in selectedDop)
            {
                model.SelectedDopUslug.Add(item);
            }
            if (tour.People >= tour.AllPeople && tour.AllPeolpeFake != 0)
            {
                tour.People = tour.People.Value - tour.AllPeolpeFake.Value;
                tour.AllPeolpeFake = 0;
            }
            if (tour.People <= tour.AllPeople)
            {
                if (Request.IsAuthenticated)
                {
                    int userID = WebSecurity.GetUserId(User.Identity.Name);
                    UserProfile userprofile = db.UserProfiles.Find(userID);
                    if (userprofile.Bonus != null || userprofile.Bonus != 0)
                    {
                        if (userprofile.Bonus <= model.BonusPay)
                        {
                            Price -= userprofile.Bonus.Value;
                            model.UsersBonus = userprofile.Bonus.Value;
                            userprofile.Bonus -= userprofile.Bonus;
                            db.Entry(userprofile).State = EntityState.Modified;
                        }
                        if (userprofile.Bonus > model.BonusPay)
                        {
                            Price -= model.BonusPay.Value;
                            userprofile.Bonus -= model.BonusPay;
                            model.UsersBonus = model.BonusPay;
                            db.Entry(userprofile).State = EntityState.Modified;
                        }
                    }
                }
                Price = decimal.Parse( String.Format("{0:0.00}",Price));
                if (model.TourPrice == Price)
                {
                    model.Status = "Не оплачена";
                    model.DateTourId = int.Parse(DateTourId);
                    if (Request.IsAuthenticated)
                    {
                        int userID = WebSecurity.GetUserId(User.Identity.Name);
                        UserProfile userprofile = db.UserProfiles.Find(userID);
                        userprofile.Trips = new List<Trip>();
                        userprofile.Trips.Add(model);
                        db.Entry(userprofile).State = EntityState.Modified;
                    }
                    tour.Trips = new List<Trip>();
                    tour.Trips.Add(model);
                    if (!Request.IsAuthenticated)
                    {
                        int anonimusID = WebSecurity.GetUserId("Anonimus@mail.com");
                        UserProfile anonimus = db.UserProfiles.Find(anonimusID);
                        anonimus.Trips = new List<Trip>();
                        anonimus.Trips.Add(model);
                        db.Entry(anonimus).State = EntityState.Added;
                    }
                    tour.People = tour.People.Value + 1;
                    db.Entry(tour).State = EntityState.Modified;
                    db.Entry(model).State = EntityState.Added;
                    db.SaveChanges();
                    return RedirectToAction("Payment", new { id = model.TripID });
                }
                else
                    return RedirectToAction("Error", "Error");
            }
            else
                return RedirectToAction("Максимальное количество людей");
        }
        public ActionResult DopPricePartial(int id = 0)
        {
            var data = db.DopUslugs.Where(m => m.TourId == id);

            return View(data);
        }
        public ActionResult Payment(int id, int? counterBuy)
        {
            if (counterBuy == 1)
            {
                ViewBag.CounterBuy = 1;
            }
            var data = db.Trip.Find(id);
            var dataTour = db.Tour.Find(data.TourId);
            var dataObj = new
            {
                version = 3,
                public_key = "i69833650669",
                amount = data.TourPrice,
                currency = "UAH",
                description = dataTour.NameTour,
                order_id = data.TripID,
                pay_way = "card,liqpay,delayed,invoice,privat24",
                language = "ru",
                server_url = "http://kote.travel/Buy/ValValidatePay",
                result_url = "http://kote.travel/Profile/Profile"
            };

            System.Web.Script.Serialization.JavaScriptSerializer serializer = new System.Web.Script.Serialization.JavaScriptSerializer();
            string dataJson = serializer.Serialize(dataObj);
            byte[] bytes = System.Text.Encoding.UTF8.GetBytes(dataJson);
            string dataStr = System.Convert.ToBase64String(bytes);
            string privateKey = "v2Rhrz287rrJtDSHq228gsg70ZkA8omC2mhl7aha";
            var signature = privateKey + dataStr + privateKey;

            SHA1 sha1 = SHA1.Create();
            byte[] hash = sha1.ComputeHash(System.Text.Encoding.UTF8.GetBytes(signature));

            ViewBag.Data = dataStr;
            ViewBag.Signature = System.Convert.ToBase64String(hash);
            AuthenticationResult result = OAuthWebSecurity.VerifyAuthentication();
            ViewBag.UserIDI = result.ProviderUserId;
            return View(db.Trip.Where(m => m.TripID == id).Include(m => m.DateTour).Include(m => m.SelectedDopUslug).Include(m=>m.Tour).Single());
        }
        [HttpPost]
        public ActionResult ValidatePay(string data, string signature)
        {
            string privateKey = "v2Rhrz287rrJtDSHq228gsg70ZkA8omC2mhl7aha";
            byte[] dataByte = Convert.FromBase64String(data);
            string dataStr = Encoding.UTF8.GetString(dataByte);
            TripJS obj = JsonConvert.DeserializeObject<TripJS>(dataStr);

WorkWithKOTE/Views/Buy/DopPricePartial.cshtml
@model IEnumerable<WorkWithKOTE.Models.DopUslug>
@{
    Layout = null;
}
<div id="options">
    @{
        int i = 0;
    }
    <ul style="list-style:none">
        @foreach (var item in Model)
        {
            if (item.Price != 0)
            {
                string name = "ItemChecked" + i;

                <li class="dopu" id="options">
                    <input type="checkbox" class="css-checkbox" name="Item" value="@item.DopUslugId" id="@name" data-price="@item.Price" onclick=" Check() " />
                    <label for="@name" class="css-label"> @item.Name&nbsp;(@item.Price)</label>
                </li>

                i++;
            }
        }
    </ul>
</div>

<script>
    $(function(){
         if ($('#bar').width() <= 800) {
             $('.dopu').css('min-height','80px');
         }
         else {
             $('.dopu').css('min-height', '40px');
         }

         $(window).resize(function () {
             if ($('#bar').width() <= 800) {
                 $('.dopu').css('min-height', '80px');
             }
             else {
                 $('.dopu').css('min-height', '40px');
             }
         });
    });
</script>

WorkWithKOTE/Views/Buy/Payment.cshtml
@{
    ViewBag.Title = "kote.travel - Оплата";
}
@model WorkWithKOTE.Models.Trip
@Styles.Render("~/Content/form")
@Styles.Render("~/Content/order")
<script src="//vk.com/js/api/openapi.js" type="text/javascript"></script>
<script src="view-source:http:/connect.facebook.net/en_US/all.js" type="text/javascript"></script>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js" type="text/javascript"></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">

<style>
    .payBtn {
        padding: 5px !important;
        border-radius: 4px !important;
        background-color: #ff6f40 !important;
        border: 1px solid #ff6f40 !important;
        color: white !important;
        height: 30px !important;
        cursor: pointer !important;
        margin-top: 10px !important;
        margin-bottom: 10px !important;
        display: inline-block !important;
    }

    input[name=btn_text] {
        margin-bottom: 20px;
        margin-top: 10px;
        cursor: pointer;
        margin-left: 21%;
        width: 172px;
    }

    .infos {
        font-size: 18px;
        margin-top: 6px;
        display: block;
    }

    #orderText {
        font-size: 20px;
        margin-left: -20px;
        text-decoration: underline;
    }

    .container {
        margin-left: 21%;
    }

     .VkontakteDialog{
       border-radius: 4px;
       margin-top : 15px;
       height: 33.5px;
       font-size: 14px;
       background-color : #6383a8 !important;  
       background: no-repeat;
       background-image : url("/Content/img/vk.png"); 
       color : white !important;
       width : 250px;
       text-align : right;
        display:inline-block;
       border : 1px solid #6383a8;
    }

    .facebookDialog{
       margin-top: 15px;
       border-radius: 4px;
       height: 33.5px;
       font-size: 14px;
       background-color : #6383a8 !important;
       background: no-repeat;
       background-image : url("/Content/img/facebook.png");     
       color : white !important;
       width : 250px;
       text-align : right;
       display:inline-block;
       border : 1px solid #6383a8;    
    }

     .ui-dialog.ui-widget.ui-widget-content.ui-corner-all.ui-front.ui-draggable.ui-resizable{
        width: 353px !important;
    }

    .ui-dialog-titlebar{
        background : white;
        border : none;
        font-size : 15px;
    }

    .ui-dialog-title{
        padding-left : 2px;
    }

    .ui-dialog{
          box-shadow: 1px 1px 2px 0px #ccc;
    }
</style>

@{ Html.RenderPartial("HeaderPartial_main");}

<div id="small-preview-img" class="clearfix">
    <hgroup>
        <h1>Оплата</h1>
        <h2>@Html.ActionLink("Главная", "Index", "Home", null, null) / <span id="currentZ">Оплата</span> </h2>
    </hgroup>
</div>

<div class="container">

    <span id="orderText"> Информация о Вашем туре : </span>

    <div class="infos">Название тура : "@Html.DisplayFor(m => m.Tour.NameTour)"</div>
    <div class="infos">Дата тура : @Html.DisplayFor(m => m.DateTour.FirstDate) - @Html.DisplayFor(m => m.DateTour.SecondDate)</div>
    <div class="infos">Стоимость поездки : @Html.DisplayFor(m => m.Tour.Cost)  @Html.DisplayFor(m => m.Valuta) </div>

    @foreach (var item in Model.SelectedDopUslug)
    {
        <div class="infos">
            @Html.DisplayFor(m => item.SelectedDopUslugName) ( стоимость : @Html.DisplayFor(m => item.SelectedDopPrice) @Html.DisplayFor(m => m.Valuta) )
        </div>
    }
    <div class="infos">Стоимость с учётом дополнительных услуг : <strong> @Html.DisplayFor(m => m.TourPrice)  UAH </strong></div>

    <div id="fb-root">
    </div>
    @if (Request.IsAuthenticated && ViewBag.CounterBuy != 1)
    {
      <div id="shareBlock" style="display:none;">
        <span  style="font-size:15px;">Расскажите о нас и получите бонусные баллы на свой счёт!</span>
        <input type="button" id="share_button" class="facebookDialog" value="Поделиться Facebook" />
        <input type="button" class="VkontakteDialog" value="Поделиться Вконтакте" onclick="postapi()" id="share_VK" />
    </div>   
    }
    <input class="payBtn" type="button" value="Изменить информацию" onclick="location.href='@Url.Action("TripEdit", "Buy", new { IdTrip = Model.TripID })'" />
    <input class="payBtn" type="button" value="Вернуться в Профиль" onclick="location.href='@Url.Action("Profile","Profile",null)'" />
</div>
<script type="text/javascript">
    var TourLink = 'http://kote.travel/TourDisplay/Index/' + '@Model.TourId';
    VK.init({
        apiId: 4913176
    });
    function postapi() {
        VK.Api.call('wall.post', { message: "Я КОТЭшествую в @Model.Tour.NameTour. Присоиденяйтесь!! Со мной уже едут  @Model.Tour.People человек ", attachments: "photo-30598666_365322387,http://kote.travel/Home/Index" },
        function (r) {
            if (r.response) {
                window.location.href = '@Url.Action("Bonuses", "Home", new { TourRepostID = 1, id = Model.TripID })'
            }
        })
    };
</script>
<script type="text/javascript">
    window.fbAsyncInit = function () {
        FB.init({
            appId: '878101295595387', status: true, cookie: true,
            xfbml: true
        });
    };
    (function () {
        var e = document.createElement('script'); e.async = true;
        e.src = document.location.protocol +
        '//connect.facebook.net/en_US/all.js';
        document.getElementById('fb-root').appendChild(e);
    }());
</script>
<script type="text/javascript">
    var img = 'http://kote.travel/' + '@Model.Tour.TourImg';
    var TourLink = 'http://kote.travel/TourDisplay/Index/' + '@Model.TourId';
    $(document).ready(function () {
        $('#share_button').click(function (e) {
            e.preventDefault();
            FB.ui(
{
    method: 'feed',
    name: 'КОТЭшествуй',
    link: TourLink,
    picture: img,
    caption: 'Только интересныйе Туры! КОТЭшествуй с нами',
    description: 'Я КОТЭшествую в @Model.Tour.NameTour. Присоиденяйтесь!! Со мной уже едут  @Model.Tour.People человек',
    message: 'Присоединяйтесь!'
},
  function (response) {
      if (response && response.post_id) {
          window.location.href = '@Url.Action("Bonuses", "Home", new { TourRepostID = 1 , id = Model.TripID })'
      }
  });
        });
    });
</script>
<form method="POST" accept-charset="utf-8" action="https://www.liqpay.com/api/checkout">
    <input type="hidden" name="data" value="@ViewBag.Data" />
    <input type="hidden" name="signature" value="@ViewBag.Signature" />
    <input type="image" src="//static.liqpay.com/buttons/p1ru.radius.png" name="btn_text" />
</form>

<script>
    $(function () 
    {
        $("#shareBlock").dialog({
            title: "РАССКАЗАТЬ О KOTЕ",
            modal: true,
            resizable: false,
            draggable: false
        });
    });
</script>