WorkWithKOTE/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WorkWithKOTE.Models;
using WorkWithKOTE.Code;
using System.Data;
using System.Data.Entity;

namespace WorkWithKOTE.Controllers
{
    public class GalleryController : Controller
    {
        //
        // GET: /Gallery/
        UsersContext db = new UsersContext();
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult CreateGallery()
        {
            return View();
        }
        [HttpPost]
        public ActionResult CreateGallery(Gallery model, HttpPostedFileBase[] file)
        {
            List<HttpPostedFileBase> Files = new List<HttpPostedFileBase>();
            for (int i = 0; i < file.Length; i++)
            {
                if (file[i] != null)
                   model.Pics[i].PicLink = UploadImages.UploadImg(file[i], "/Upload/Gallery/");

            }
            db.Entry(model).State = EntityState.Added;
            db.SaveChanges();
            return RedirectToAction("GalleryList");
        }
        public ActionResult GalleryList()
        {
            return View(db.Gallery.Include(m=>m.Pics));
        }
        public ActionResult Gallery(int id)
        {
            return View(db.Gallery.Include(m => m.Pics).Where(m => m.GalleryId == id).Single());
        }
        [Authorize(Roles = "Admin, Moderator")]
        public ActionResult GalleryDelete(int id)
        {
            var gallery = db.Gallery.Find(id);
            db.Gallery.Remove(gallery);
            db.SaveChanges();
            return RedirectToAction("GalleryList");
        }
    }
}

WorkWithKOTE/Controllers/TourSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WorkWithKOTE.Models;
using System.Data.Entity;
using PagedList;
using PagedList.Mvc;
namespace WorkWithKOTE.Controllers
{
    public class TourSearchController : Controller
    {
        //
        // GET: /TourSearch/
        // TourContext db = new TourContext();
        UsersContext db = new UsersContext();
        public ActionResult Search()
        {
            return View(db.Tour.Include(m => m.DateTour).ToList());
        }

        [HttpPost]
        public ActionResult Search(String Tag, String Date = null, String TypeOfTour = null, String ArrivePlace = null, bool IsCar = false, bool IsShip = false, bool IsTrain = false, bool IsPlane = false, string Prices = null)
        {
            IQueryable<Tour> data = db.Tour;
            if (!String.IsNullOrEmpty(Date))
            {
                int month = int.Parse(Date);
                data = data.Where(m => m.DateTour.Any(dt => dt.FirstDate.Month == month));
            }
            if (!String.IsNullOrEmpty(TypeOfTour))
            {
                int typeTourId = int.Parse(TypeOfTour);
                data = data.Where(m => m.TypeOfTourId == typeTourId);
            }
            if (!String.IsNullOrEmpty(ArrivePlace))
            {
                data = data.Where(m => m.PlaceOfArrival == ArrivePlace);
            }
            if (!String.IsNullOrEmpty(Tag))
            {
                string[] separator = { ",", ".", ";", " " };
                string[] TagMass = Tag.Split(separator, StringSplitOptions.RemoveEmptyEntries);
                foreach (var item in TagMass)
                {
                    data = data.Where(m => m.Tag.Any(t => t.TagName == item));
                }
            }
            if (IsCar == true)
                data = data.Where(m => m.IsBus == true);
            if (IsPlane == true)
                data = data.Where(m => m.IsAriplane == true);
            if (IsShip == true)
                data = data.Where(m => m.IsShip == true);
            if (IsTrain == true)
                data = data.Where(m => m.IsTrain == true);
            if (!String.IsNullOrEmpty(Prices))
            {
                decimal price = decimal.Parse(Prices);
                data = data.Where(m => m.Cost >= price);
            }
            return View(data.Include(m => m.DateTour));
        }
        public ActionResult Searches(int page = 0, int ourCounter = 0 )
        {
            if (ourCounter == 0)
            {
                ViewBag.Counter = 0;
                ViewBag.MinValue = 1000;
                ViewBag.MaxValue = 3000;
                int pageNumber = 1;
                if (page != 0)
                    pageNumber = page;
                int pageSize = 6;
                var data = db.Tour.Include(m => m.DateTour).Include(m => m.Tag).ToList();
                return View(data.ToPagedList(pageNumber, pageSize));
            }
            else
            {
               int  pageNumber  = page;
                int PageSize = 6 ;
                return Searches(page = pageNumber  );
            }
           
        }
        [HttpPost]
        public ActionResult Searches(string PlaceDepartmen, string Places, string DateFirst, string DateFirstt, string DateSecond, decimal? MinValue, decimal? MaxValue, bool IsCar = false, bool IsShip = false, bool IsTrain = false, bool IsPlane = false, int page = 0, string[] Tags = null)
        {
            ViewBag.Counter = 1;
            // IQueryable<Tour> data = db.Tour;
            IEnumerable<Tour> data = db.Tour.Include(m => m.DateTour).Include(m => m.Tag).Include(m => m.Places).AsEnumerable();
            var actualRates = db.Curseds.First();
            Dictionary<string, decimal> rates = new Dictionary<string, decimal>();
            rates.Add("UAH", 1);
            rates.Add("USD", actualRates.USD);
            rates.Add("EUR", actualRates.Evro);
            if (!String.IsNullOrEmpty(Places))
            {
                ViewBag.Place = Places;
                data = data.Where(m => m.PlaceOfArrival.Contains(Places) || m.Places.Any(k => k.PlaceName.Contains(Places)));
            }
            if (!String.IsNullOrEmpty(PlaceDepartmen))
            {
                data = data.Where(m => m.PlaceOfDeparture.Contains(PlaceDepartmen));
            }
            if (!String.IsNullOrEmpty(DateFirst))
            {
                int month = int.Parse(DateFirst);
                data = data.Where(m => m.DateTour.Any(dt => dt.FirstDate.Month == month));
            }

            if (!String.IsNullOrEmpty(DateFirstt))
            {
                ViewBag.DateFirst = DateFirstt;
                DateTime dateMin = DateTime.ParseExact(DateFirstt, "dd.MM.yyyy", System.Globalization.CultureInfo.InvariantCulture).AddDays(-5);
                DateTime dateMax = DateTime.ParseExact(DateFirstt, "dd.MM.yyyy", System.Globalization.CultureInfo.InvariantCulture).AddDays(5);
                data = data.Where(m => m.DateTour.Any(dt => dt.FirstDate >= dateMin && dt.FirstDate <= dateMax));
            }
            if (!String.IsNullOrEmpty(DateSecond))
            {
                ViewBag.DateSecond = DateSecond;
                DateTime dateMin = DateTime.ParseExact(DateSecond, "dd.MM.yyyy", System.Globalization.CultureInfo.InvariantCulture).AddDays(-5);
                DateTime dateMax = DateTime.ParseExact(DateSecond, "dd.MM.yyyy", System.Globalization.CultureInfo.InvariantCulture).AddDays(5);
                data = data.Where(m => m.DateTour.Any(dt => dt.SecondDate >= dateMin && dt.SecondDate <= dateMax));
            }
            if (MinValue != null)
            {
                ViewBag.MinValue = MinValue;
                data = data.Where(m => (m.Cost * rates[m.Valuta]) >= MinValue || m.AukcionPrice >= MinValue);
            }
            if (MaxValue != null)
            {
                ViewBag.MaxValue = MaxValue;
                data = data.Where(m => (m.Cost * rates[m.Valuta]) <= MaxValue || m.AukcionPrice <= MaxValue);
            }
            if (IsCar == true)
                data = data.Where(m => m.IsBus == true);
            if (IsPlane == true)
                data = data.Where(m => m.IsAriplane == true);
            if (IsShip == true)
                data = data.Where(m => m.IsShip == true);
            if (IsTrain == true)
                data = data.Where(m => m.IsTrain == true);
            if (Tags != null)
            {
                foreach (var item in Tags)
                {
                    data = data.Where(m => m.Tag.Any(tg => tg.TagName == item));
                }
            }
            var places = data.Select(m => m.PlaceOfDeparture).Distinct();

            List<string> list = new List<string>();
            if (places.Any())
            {
                foreach (var item in places)
                {
                    list.Add(item);
                }
            }
            ViewBag.PlaceDeparture = list;
            /*  if (PageCount != 0 && PageID != 0)
              {
                  return View(data.Skip(PageCount * PageID).Take(PageCount));
              }
              if (HomeCounter == 1)
              {
                  return View(data);
              }*/
            int pageNumber = 1;
            if (page != 0)
                pageNumber = page;
            int pageSize = 6;
            data = data.ToList();
            return View(data.ToPagedList(pageNumber, pageSize));
        }
    }
}

WorkWithKOTE/Views/Shared/HeaderPartial.cshtml
    <header>
    <div id="bar">
        <img id="small-logo" src="~/Content/img/small-logo.png" />

        <nav>
            @Html.ActionLink("Главная", "Index", "Home", null, null)
            @Html.ActionLink("Туры", "Search", "TourSearch", null, null)
            <a href="#">Галерея</a>
            <a href="#">Контакты</a>
        </nav>
        <img src="~/Content/img/separator.png" class="separator" />

        <div class="profile">
            <div class="user">
                <img id="user" src="~/Content/img/user.png" />
                @if (Request.IsAuthenticated)
                {
                    @Html.ActionLink(User.Identity.Name, "Profile", "Profile", null, new { @class = "username" })
                }
                else
                {
                    @Html.ActionLink("Войти", "Login", "Account", null, new { @class = "username" })
                }
            </div>
        </div>
        <img src="~/Content/img/separator.png" class="separator" />
        <a href="#"><img id="Searching" src="~/Content/img/Searching.png" /></a>
    </div>
        <img id="top-shadow" src="~/Content/img/top-shadow.png" />
</header>
<style>
    header {
        color: black;
        background-color: white;
    }
     
</style>

WorkWithKOTE/Views/Shared/HeaderPartial_main.cshtml
@using WorkWithKOTE.Code
<style>

    #forMenu{
        cursor : pointer;
    }

    .selectize.whereCopy  {
        display: inline-block;
        width: 47%;
        height: 40px;
        background: #656d78;
        color: #e6e9ed;
        line-height: 17px;
        font-size: 16px;
        border: 1px solid #3e4753;
        margin-left: 17px;
    }

       .selectize-control.selectize.whereCopy > .selectize-input {
        margin: 5px 0px -14px 0px;
        background: none;
        border: none;
        padding: 0px;
        width: 90%;
    }

    .selectize-control.selectize.whereCopy > .selectize-input.focus {
        background: none;
        border: none;
        color: #e6e9ed;
        box-shadow: none;
    }
   .selectize-control.selectize.whereCopy > .selectize-input.full {
        background: none;
        border: none;
        color: #e6e9ed;
    }
    .selectize-control.selectize.whereCopy > .selectize-input input {
        color: #e6e9ed;
        line-height: 14px;
        font-size: 16px;
        background: none !important;
        box-shadow: none !important;
    }

    .selectize-control.selectize.whereCopy > .selectize-input input ::-webkit-input-placeholder {
        color: #e6e9ed;
        line-height: 14px;
        font-size: 16px;
    }

    .selectize-control.selectize.whereCopy > .selectize-input input ::-moz-placeholder {
        color: #e6e9ed;
        line-height: 14px;
        font-size: 16px;
    }
    /* Firefox 19+ */
   .selectize-control.selectize.whereCopy > .selectize-input input :-moz-placeholder {
        color: #e6e9ed;
        line-height: 14px;
        font-size: 16px;
    }
    /* Firefox 18- */
   .selectize-control.selectize.whereCopy > .selectize-input input :-ms-input-placeholder {
        color: #e6e9ed;
        line-height: 14px;
        font-size: 16px;
    }

   .selectize-control.selectize.whereCopy > .selectize-input input .selectize-input.focus {
        box-shadow: none;
    }

    .selectize-control.selectize.whereCopy > .selectize-input,
    .selectize-control.single.whereCopy .selectize-input.input-active {
        background: none;
        border: none;
        width: 100%;
    }

   .selectize-dropdown.whereCopy {
        font-size: 16px !important;
        position: absolute;
        z-index: 10;
        /*border: 1px solid #eaeaea;*/
        background: #656d78;
        margin: -1px 0 0 0;
        border-top: 0 none;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
        -webkit-box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
        -webkit-border-radius: 0 0 2px 2px;
        -moz-border-radius: 0 0 2px 2px;
        border-radius: 0 0 2px 2px;
        width:100% !important;
        height: auto;
        margin-left: 0px !important;
     /*   top: 39px !important;
        left: 0px !important;*/
    }

       .selectize-dropdown.whereCopy .active {
        background: #3e4753;
        color: #e6e9ed;
    }

     .whereCopy{
        position: absolute !important;
        color: white !important;
        background-color: white !important;
        width: 216px !important;
        margin-top: -6px !important;
        margin-left: 32px !important;
        text-align: left !important;
        padding-left: 7px !important;
        line-height: 21px !important;
    }
    
    #tiny_menu{
        display : none;
        margin-top: -27px;
        background: white;
        box-shadow: 1px 1px 3px 0px #ccc;
        position: absolute;
        width: 150px;
        height: 150px;
    }

    .menuLink,.menuLink_first {
        font-size : 20px;
        padding-top:20px;
    }

    #second-navigation{
        width:100%;
        min-height : 42px;
    }

    #sec_nave{
        font-size : 18px !important;
        margin-top : 10px;
    }

    .Vkontakte{
       border-radius: 4px;
       margin-top : 5px;
       height: 33.5px;
       font-size: 14px;
       background : #6383a8 no-repeat;
       background-image : url("/Content/img/vk.png");     
       color : white;
       width : 212px;
       text-align : right;
       border : 1px solid #6383a8;
    }

    .facebook{
       margin-top: 5px;
       border-radius: 4px;
       height: 33.5px;
       font-size: 14px;
       background : #6383a8 no-repeat;
       background-image : url("/Content/img/facebook.png");     
       color : white;
       width : 202px;
       text-align : right;
       border : 1px solid #6383a8;    
    }

    #searchIcon{
        cursor : pointer;
    }

    .whereCopy > input[type=text]{
        width : auto !important;
    }

    .selectize-dropdown.whereCopy{
       width: 214px !important;
       top: 52px !important;
       left: 0px !important;
    }

    .selectize-control.selectize.whereCopy{
        opacity : 0;
        transition :0.4s;
        border-radius : 7px;
    }

    .selectize.whereCopy{
        visibility:hidden;
    }

    .selectize-dropdown.whereCopy > .selectize-dropdown-content{
        margin-left : -7px !important;
        background-color : #656d78;
    }

    .selectize-control.selectize.whereCopy > .selectize-input.items.not-full.has-options{
      margin-left: -5px !important;
      padding-left: 8px !important;
      height: 33px !important;
    }

    div[data-value]{
        color : darkgrey;
    }
   
</style>

<header>
    <div id="bar">
        <a href="@Url.Action("Index","Home")"><img id="small-logo" src="~/Content/img/small-logo.png" /></a>

        <nav id="navigation">
            @Html.ActionLink("Главная", "Index", "Home", null, null)
            @Html.ActionLink("Туры", "Searches", "TourSearch", null, null)
            @Html.ActionLink("Галерея", "GalleryList", "Gallery", null, null)
            @Html.ActionLink("О нас", "Contact", "Home", null, null)
        </nav>

        <div class="profile">
            <div class="user">
                <img src="~/Content/img/separator.png" class="separator" />
             
                @if (Request.IsAuthenticated)
                {
                    <span id="user_name">@User.Identity.Name</span>
                      <div id="block_links" class="hidden">
                          <a href='@Url.Action("Profile","Profile")' class="user_links">Профиль</a>
                          <a href='@Url.Action("LogOff", "Account")' class="user_links">Выход</a>
                      </div>
                }
                else
                {
                    <span id="user_name">Вход в личный кабинет </span>
                      <div id="block_enter" class="hidden">
                         <div id="blockExt">
                             @Html.Action("ExternalLoginsList","Account", new { ReturnUrl = ViewBag.ReturnUrl })
                         </div>

                         @using (Html.BeginForm("Login", "Account", FormMethod.Post, new { ReturnUrl = ViewBag.ReturnUrl, @id = "signForm" }))
                         {
                              @Html.AntiForgeryToken();
                              <input name="Email" type="text" class="input_log_in notHide" placeholder="Логин" />
                              <input name="Password" type="password" class="input_log_in notHide" placeholder="Пароль" />
                              <input id="enter_button" type="submit" value="Войти" class="notHide" />
                          
                         }
                          <a href='@Url.Action("Register","Account")' id="register" class="user_links_e">Регистрация</a>
                          <a href='@Url.Action("ForgotPassword","Profile")' id="amnesia" class="user_links_e">Забыли пароль ?</a>
                      </div>
                }
                <img src="~/Content/img/separator.png" class="separator" />
                <img style="width:20px;height:10px;display:none;" src="~/Content/img/menuicon.png" id="forMenu" />
            </div>
        </div>

        <div id="tiny_menu">
            <p class="menuLink_first"> @Html.ActionLink("Главная", "Index", "Home", null, null)          </p>
            <p class="menuLink">       @Html.ActionLink("Туры", "Searches", "TourSearch", null, null)      </p>
            <p class="menuLink">       @Html.ActionLink("Галерея", "GalleryList", "Gallery", null, null) </p>
            <p class="menuLink">       @Html.ActionLink("Новости", "AllNewsBlock", "News",null,null)     </p>
            <p class="menuLink">       @Html.ActionLink("О нас", "Contact", "Home", null, null)          </p>

           <!-- <p class="menuLink">
                <a href="@Url.Action("Searches", "TourSearch")">Поиск</a>
            </p>
               -->
        </div>
    
        <a id="searchIcon"><img id="Searching" src="~/Content/img/Searching.png" /></a>
        <form id="searchFormCopy" action="@Url.Action("Searches","TourSearch")" method="post" enctype="multipart/form-data">
            @Html.DropDownList("Places", DropDown.Places(), "Куда", new { @id = "where", @class = "selectize whereCopy" })
        </form>
</div>
    <img id="top-shadow" src="~/Content/img/top-shadow.png"/>
    <div id="second-navigation">
    <div class="groupLinks" id="sec_nave">
        <a href="#first">по Украине</a>
        <a href="#second">в Грузию</a>
        <a href="#third">Приключенческие</a>
    </div>
</div>
</header>

<script>
    $(function ()
    {
        $('#blockExt button').css({ 'width': '40.5%', 'display': 'inline' }).text('Войти');
        $('#blockExt button:first').css('margin-left', '20px');

        if ($('#bar').width() <= 800)
        {
            $('.nav-other a,#Searching,#navigation').hide();
            $('.profile').css('margin-top', '25px');
            $('#forMenu').show().css('display','inline');
        }
        else {
            $('.nav-other a,#Searching,#navigation').show();
            $('#forMenu').hide();
            $('.profile').css('margin-top', '0px');
            $('#tiny_menu').hide(500);
        }

        if ($('#bar').width() <= 450) {
            $('#small-logo').hide();
        }

        $(window).resize(function ()
        {

            $('#tiny_menu').hide(500);

            if ($('#bar').width() <= 800) {
                $('.nav-other a,#Searching,#navigation').hide();
                $('.profile').css('margin-top', '25px');
                $('#forMenu').show().css('display', 'inline');
            }
            else {
                $('.nav-other a,#Searching,#navigation').show();
                $('#forMenu').hide();
                $('.profile').css('margin-top', '0px');
                $('#tiny_menu').hide(500);
            }

            if ($('#bar').width() <= 450) {
                $('#small-logo').hide();
            }
            else {
                $('#small-logo').show();
            }
        });
    });

    $(function ()
    {
       
        $('body').click(function (event) {
            if ($(event.target).attr('id') != 'tiny_menu' && !$(event.target).hasClass('user')) {
                $('#tiny_menu').removeClass('opened');
                $('#tiny_menu').animate({ 'height': '0px' }, 400);
            }
        });

        $(window).scroll(function () {
            $('#tiny_menu').hide(300);
        });

        $('#forMenu').click(function () {
            $('#tiny_menu').offset({ 'left': $('#forMenu').offset().left - 130 });
            if (!$('#tiny_menu').hasClass('opened')) {
                 $('#tiny_menu').css('display', 'block').animate({ 'height': '240px' }, 400);
                 $('#tiny_menu').addClass('opened');
            }
            else {
                $('#tiny_menu').removeClass('opened');
                $('#tiny_menu').css('display', 'none').animate({ 'height': '0px' }, 400);
            }
            return false;
        });

    });

    $(function () {
        $('#searchIcon').click(function () {
            if (!$('.selectize-control.selectize.whereCopy').hasClass('visibl')) {
                $('.selectize-control.selectize.whereCopy').css({ 'opacity': '1' }).addClass('visibl');
                $('.selectize.whereCopy').css('visibility', 'visible');
            }
            else {
                $('.selectize-control.selectize.whereCopy').css('opacity', '0').removeClass('visibl');
            }
        });
        $('select.selectize').selectize({
            openOnFocus: false
        });

        $('body').keypress(function (event) {
            if (event.keyCode == '13' && $('.selectize.whereCopy.selectized').val()) {
                $('#searchFormCopy').submit();
            }
        });
    });
</script>

WorkWithKOTE/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/galleria")
    @Scripts.Render("~/bundles/common")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
@*    <script src="//code.jquery.com/jquery-1.10.2.js"></script>*@
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="/Content/js/datepicker-ru.js"></script>
    <script type="text/javascript" src="/Content/js/selectize/js/standalone/selectize.min.js"></script>
    <link rel="stylesheet" type="text/css" href="/Content/js/selectize/css/selectize.css" />
@*    <link rel="stylesheet" href="/resources/demos/style.css">*@
</head>

<body>
    <div class="primaryContainer clearfix">
        @RenderBody()
    </div>

    <footer>
        <div class="cont">
            <div id="column1" class="clearfix">
                <p id="about">
                    kote.travel - это уникальный в своем роде сервис выбора путешествий!
                    У нас вы точно найдете только лучшие туры, походы, фестивали, экспедиции по Украине и всему миру!
                    Над созданием сервиса трудятся профессионалы сферы туризма (ученые, путешественники, турменеджеры, гиды).
                    Мы отбираем только самое интересное и уникальное для Вас.
                </p>
            </div>
            <div id="column2">
                <div id="footer-nav">
                    @Html.ActionLink("Главная", "Index", "Home", null, null)
                    @Html.ActionLink("Туры", "Searches", "TourSearch", null, null)
                    @Html.ActionLink("Галерея", "GalleryList", "Gallery", null, null)
                    @Html.ActionLink("О Нас", "Contact", "Home", null, null)
                </div>

                <div id="follow-us">
                    <p>Следи за нами&#x3a;</p>
                    <a target="_blank" href="https://vk.com/kotetur"><img src="~/Content/img/vk.png" class="image-icons" /></a>
                    <a target="_blank" href="https://plus.google.com/u/0/118122030268269531704/posts">
                        <img src="~/Content/img/google.png" class="image-icons" />
                    </a>
                    <a target="_blank" href="https://www.facebook.com/kotetravel"><img src="~/Content/img/facebook.png" class="image-icons" /></a>
                </div>

            </div>
            <div id="column3" class="clearfix">
                <div id="contacts">
                    <h5>Консультант&#x3a;</h5>
                      <p class="phone">&#x2b;38 <span class="phone-code">097</span>-815-68-38</p>
                      <p class="phone">&#x2b;38 <span class="phone-code">050</span>-774-99-18</p>
                      <p class="phone">&#x2b;38 <span class="phone-code">063</span>-796-25-00</p>
                    <br/>

                    <h5>Наша почта&#x3a;<br /></h5>
                      <p class="mail">kote.travel&#x40;gmail.com</p>
                    <br />

                    <h5>Skype&#x3a;<br /></h5>
                      <p class="mail">kote.travel</p>
                </div>
            </div>
        </div>
    </footer>

    <div id="copy-bg" class="clearfix">
        <div id="copyrighter">
            <span id="copyright">&copy; 2015 </span>
            <span id="copyright-site">kote.travel<br /></span>
            <span id="rights">Все права защищены</span>
        </div>
    </div>
    @RenderSection("scripts", required: false)
    <!-- BEGIN JIVOSITE CODE {literal} -->
    <script type='text/javascript'>
        (function () {
            var widget_id = 'i1bSpOH4ty';
            var s = document.createElement('script'); s.type = 'text/javascript'; s.async = true; s.src = '//code.jivosite.com/script/widget/' + widget_id; var ss = document.getElementsByTagName('script')[0]; ss.parentNode.insertBefore(s, ss);
        })();</script>
    <!-- {/literal} END JIVOSITE CODE -->
</body>
</html>


<script>
    $(function () {
        if ($('footer').width() <= 800) {
            $('#column1,#follow-us').hide();
            $('#column2').css('margin-left', '15%');
            $('#footer-nav a').css({ 'float': 'none', 'display': 'block', 'width': 'auto' });
            $('#footer-nav a').not(':first').css('margin-top', '20px');
        }

        $(window).resize(function ()
        {
            if ($('footer').width() <= 800)
            {
                $('#column1,#follow-us').hide();
                $('#column2').css('margin-left', '15%');
                $('#footer-nav a').css({ 'float': 'none', 'display': 'block', 'width': 'auto' });
                $('#footer-nav a').not(':first').css('margin-top', '25px');
            }
            else {
                $('#column1,#follow-us').show();
                $('#footer-nav a').css({ 'float': 'left', 'display': 'inline', 'width': '25%' });
                $('#footer-nav a').not(':first').css('margin-top', '0px');
                $('#column2').css('margin-left', '5%');
            }
        });
    });
</script>