WorkWithKOTE/Controllers/TourDisplayController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WorkWithKOTE.Models;
using System.Data.Entity;
namespace WorkWithKOTE.Controllers
{
    public class TourDisplayController : Controller
    {
        //
        // GET: /TourDisplay/
        UsersContext db = new UsersContext();
        public ActionResult Index(int id = 0)
        {
            if (id != 0)
            {
                var data = db.Tour.Include(m=>m.DopUslug).Include(m => m.DateTour).Include(m => m.RoutePoints).Include(m => m.Tag).Include(m => m.Trips).Include(m=>m.SameTour).Include(m=>m.Gallery.Pics).Where(m => m.TourId == id).FirstOrDefault();
                    return View(data);
            }
            return View();//Добавить страницу ошибки
        }
        public ActionResult FileDownload(int id)
        {
            var data = db.Tour.Find(id);
            string file_path = data.Document;
            string file_name = Path.GetFileName(file_path);
            string extension = "application/octet-stream";
            if (file_name != null)
                return File(file_path, extension, file_name);
            else
                return RedirectToAction("Index", id);
        }
        public ActionResult MapForDisplay(int id)
        {
            var data = db.RoutePoint.Where(m => m.TourId == id);
            return PartialView(data);
        }
        [Authorize(Roles = "Admin,Moderator")]
        public ActionResult TourDelete(int id = 0)
        {
            try
            {
                var model = db.Tour.Find(id);
                db.Tour.Remove(model);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Home");
            }
        }
    }
}

WorkWithKOTE/Controllers/TourSearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WorkWithKOTE.Models;
using System.Data.Entity;
using PagedList;
using PagedList.Mvc;
namespace WorkWithKOTE.Controllers
{
    public class TourSearchController : Controller
    {
        //
        // GET: /TourSearch/
        // TourContext db = new TourContext();
        UsersContext db = new UsersContext();
        public ActionResult Search()
        {
            return View(db.Tour.Include(m => m.DateTour).ToList());
        }

        [HttpPost]
        public ActionResult Search(String Tag, String Date = null, String TypeOfTour = null, String ArrivePlace = null, bool IsCar = false, bool IsShip = false, bool IsTrain = false, bool IsPlane = false, string Prices = null)
        {
            IQueryable<Tour> data = db.Tour;
            if (!String.IsNullOrEmpty(Date))
            {
                int month = int.Parse(Date);
                data = data.Where(m => m.DateTour.Any(dt => dt.FirstDate.Month == month));
            }
            if (!String.IsNullOrEmpty(TypeOfTour))
            {
                int typeTourId = int.Parse(TypeOfTour);
                data = data.Where(m => m.TypeOfTourId == typeTourId);
            }
            if (!String.IsNullOrEmpty(ArrivePlace))
            {
                data = data.Where(m => m.PlaceOfArrival == ArrivePlace);
            }
            if (!String.IsNullOrEmpty(Tag))
            {
                string[] separator = { ",", ".", ";", " " };
                string[] TagMass = Tag.Split(separator, StringSplitOptions.RemoveEmptyEntries);
                foreach (var item in TagMass)
                {
                    data = data.Where(m => m.Tag.Any(t => t.TagName == item));
                }
            }
            if (IsCar == true)
                data = data.Where(m => m.IsBus == true);
            if (IsPlane == true)
                data = data.Where(m => m.IsAriplane == true);
            if (IsShip == true)
                data = data.Where(m => m.IsShip == true);
            if (IsTrain == true)
                data = data.Where(m => m.IsTrain == true);
            if (!String.IsNullOrEmpty(Prices))
            {
                decimal price = decimal.Parse(Prices);
                data = data.Where(m => m.Cost >= price);
            }
            return View(data.Include(m => m.DateTour));
        }
        public ActionResult Searches(int page = 0, int ourCounter = 0 )
        {
            if (ourCounter == 0)
            {
                ViewBag.Counter = 0;
                ViewBag.MinValue = 1000;
                ViewBag.MaxValue = 3000;
                int pageNumber = 1;
                if (page != 0)
                    pageNumber = page;
                int pageSize = 6;
                var data = db.Tour.Include(m => m.DateTour).Include(m => m.Tag).ToList();
                return View(data.ToPagedList(pageNumber, pageSize));
            }
            else
            {
               int  pageNumber  = page;
                int PageSize = 6 ;
                return Searches(page = pageNumber  );
            }
           
        }
        [HttpPost]
        public ActionResult Searches(string PlaceDepartmen, string Places, string DateFirst, string DateFirstt, string DateSecond, decimal? MinValue, decimal? MaxValue, bool IsCar = false, bool IsShip = false, bool IsTrain = false, bool IsPlane = false, int page = 0, string[] Tags = null)
        {
            ViewBag.Counter = 1;
            // IQueryable<Tour> data = db.Tour;
            IEnumerable<Tour> data = db.Tour.Include(m => m.DateTour).Include(m => m.Tag).Include(m => m.Places).AsEnumerable();
            var actualRates = db.Curseds.First();
            Dictionary<string, decimal> rates = new Dictionary<string, decimal>();
            rates.Add("UAH", 1);
            rates.Add("USD", actualRates.USD);
            rates.Add("EUR", actualRates.Evro);
            if (!String.IsNullOrEmpty(Places))
            {
                ViewBag.Place = Places;
                data = data.Where(m => m.PlaceOfArrival.Contains(Places) || m.Places.Any(k => k.PlaceName.Contains(Places)));
            }
            if (!String.IsNullOrEmpty(PlaceDepartmen))
            {
                data = data.Where(m => m.PlaceOfDeparture.Contains(PlaceDepartmen));
            }
            if (!String.IsNullOrEmpty(DateFirst))
            {
                int month = int.Parse(DateFirst);
                data = data.Where(m => m.DateTour.Any(dt => dt.FirstDate.Month == month));
            }

            if (!String.IsNullOrEmpty(DateFirstt))
            {
                ViewBag.DateFirst = DateFirstt;
                DateTime dateMin = DateTime.ParseExact(DateFirstt, "dd.MM.yyyy", System.Globalization.CultureInfo.InvariantCulture).AddDays(-5);
                DateTime dateMax = DateTime.ParseExact(DateFirstt, "dd.MM.yyyy", System.Globalization.CultureInfo.InvariantCulture).AddDays(5);
                data = data.Where(m => m.DateTour.Any(dt => dt.FirstDate >= dateMin && dt.FirstDate <= dateMax));
            }
            if (!String.IsNullOrEmpty(DateSecond))
            {
                ViewBag.DateSecond = DateSecond;
                DateTime dateMin = DateTime.ParseExact(DateSecond, "dd.MM.yyyy", System.Globalization.CultureInfo.InvariantCulture).AddDays(-5);
                DateTime dateMax = DateTime.ParseExact(DateSecond, "dd.MM.yyyy", System.Globalization.CultureInfo.InvariantCulture).AddDays(5);
                data = data.Where(m => m.DateTour.Any(dt => dt.SecondDate >= dateMin && dt.SecondDate <= dateMax));
            }
            if (MinValue != null)
            {
                ViewBag.MinValue = MinValue;
                data = data.Where(m => (m.Cost * rates[m.Valuta]) >= MinValue || m.AukcionPrice >= MinValue);
            }
            if (MaxValue != null)
            {
                ViewBag.MaxValue = MaxValue;
                data = data.Where(m => (m.Cost * rates[m.Valuta]) <= MaxValue || m.AukcionPrice <= MaxValue);
            }
            if (IsCar == true)
                data = data.Where(m => m.IsBus == true);
            if (IsPlane == true)
                data = data.Where(m => m.IsAriplane == true);
            if (IsShip == true)
                data = data.Where(m => m.IsShip == true);
            if (IsTrain == true)
                data = data.Where(m => m.IsTrain == true);
            if (Tags != null)
            {
                foreach (var item in Tags)
                {
                    data = data.Where(m => m.Tag.Any(tg => tg.TagName == item));
                }
            }
            var places = data.Select(m => m.PlaceOfDeparture).Distinct();

            List<string> list = new List<string>();
            if (places.Any())
            {
                foreach (var item in places)
                {
                    list.Add(item);
                }
            }
            ViewBag.PlaceDeparture = list;
            /*  if (PageCount != 0 && PageID != 0)
              {
                  return View(data.Skip(PageCount * PageID).Take(PageCount));
              }
              if (HomeCounter == 1)
              {
                  return View(data);
              }*/
            int pageNumber = 1;
            if (page != 0)
                pageNumber = page;
            int pageSize = 6;
            data = data.ToList();
            return View(data.ToPagedList(pageNumber, pageSize));
        }
    }
}

WorkWithKOTE/Views/TourSearch/Search.cshtml
@{
    ViewBag.Title = "kote.travel - Поиск";
}
@model IEnumerable<WorkWithKOTE.Models.Tour>
@using WorkWithKOTE.Code
@Styles.Render("~/Content/order")
@{ Html.RenderPartial("HeaderPartial_main");}

<style>
    .layout{
        margin-left: 11.6%;
    }

    .date-select label.hide:after {
        display : none;
    }

    .transport p {
        margin-top : 10px;
    }

    .searchBtn{
      padding: 6px;
      color: white !important;
      border-radius : 4px;
      background-color : #ff6f40;
      border : 1px solid #ff6f40;
      color : white;
      height : 30px;
      cursor : pointer;
    }

    .tourImg:hover{
        transition : 0.1s;
        box-shadow: #ccc 1px 0px 8px 2px;
    }

     .tourImg{
        transition : 0.3s;
    }

     .titleTour{
       color : #ff6f40 !important;
       font-size : 19px;
     }

     .found-tour{
         margin-top: -38px;
     }

     .open{
         margin-left : -21.2% !important;
     }

     #filter{
      display:none;
      position: fixed;
      float: right;
      text-align: right;
      left: -42px;
      cursor: pointer;
      background-color: #ff6f40;
      color: white !important;
      transition: 0.5s;
      padding-right: 15px;
      padding-left: 15px;
      margin-top: 19px;
      padding-bottom: 7px;
      padding-top: 10px;
      width: 120px;
     }

     .rotate{
       -webkit-transform: rotate(90deg);
       -moz-transform: rotate(90deg);
       -ms-transform: rotate(90deg);
       -o-transform: rotate(90deg);
     }

</style>

<div id="small-preview-img" class="clearfix">
    <hgroup>
        <h1>Поиск</h1>
        <h2>
            <a href="@Url.Action("Index", "Home")">Главная</a> / <span id="currentZ">Поиск</span>
</h2>
    </hgroup>
</div>

<div class="container">
    <div class="layout">
        <form action="@Url.Action("Search","TourSearch")" method="post" enctype="multipart/form-data">
            <div class="layout-left-column">
             
                <p class="rotate" id="filter">Ф и л ь т р</p>

                <p>Даты</p>

                @Html.DropDownList("Date", new List<SelectListItem> { new SelectListItem{Value="1", Text="Январь"},  new SelectListItem{Value="2",Text="Февраль"}, new SelectListItem{Value="3",Text="Март"},
                 new SelectListItem{Value="4",Text="Апрель"}, new SelectListItem{Value="5",Text="Май"}, new SelectListItem{Value = "6",Text="Июнь"}, new SelectListItem{Value="7",Text="Июль"},
                 new SelectListItem{Value="8",Text="Август"}, new SelectListItem{Value="9",Text="Сентябрь"}, new SelectListItem{Value="10",Text="Октябрь"}, new SelectListItem{Value="11",Text="Ноябрь"}, new SelectListItem{Value="12",Text="Декабрь"}}, "Все даты")
            
                 <p>Типы тура</p>

                @Html.DropDownList("TypeOfTour", DropDown.SelectlistForTypeTour(), "Все туры")
                <p>Путешествие в</p>
                @Html.DropDownList("ArrivePlace", DropDown.SelectlistForArrive(), "Все направления")

                <p class="forHide">Теги</p>
                <input class="forHide" name="Tag" style="width:96%" />
                <p>Пункты назначения</p>
                @Html.DropDownList("Places",DropDown.Places(),"Любое направление")
                <p>Цена от</p>
                @Html.DropDownList("Prices", DropDown.Price(), "Любая цена")

                <p class="forHide">Транспорт</p>
                <div class="transport forHide">
                    <p>@Html.CheckBox("IsCar")&nbsp;<label for="IsCar">Автобус</label></p>
                    <p>@Html.CheckBox("IsTrain")&nbsp;<label for="IsTrain">Поезд</label></p>
                    <p>@Html.CheckBox("IsShip")&nbsp;<label for="IsShip">Лайнер</label></p>
                    <p>@Html.CheckBox("IsPlane")&nbsp;<label for="IsPlane">Самолет</label></p>
                </div><br/>

                <p style="height:30px;">
                    <a style="margin-left: 8px;" class="searchBtn" href="#" onclick=" $(this).closest('form').submit(); return false">Поиск</a>
                    @if (User.IsInRole("Admin"))
                    {
                        <a id="humanSearch" class="searchBtn" style="margin-left: 10px" href='@Url.Action("SearchAllUsers", "Admin")'>Люди</a>
                    }
                </p>
            </div><br/><br/>

            <div class="layout-main-right">
                <div class="found-tour">
                    @{
                        int index = 0;
                        bool flag = true;
                    }
                    @{ int max = Model.Count(); }
                    @foreach (var c in Model)
                    {
                        if (index >= max / 2 && flag)
                        {
                            flag = false;
                            @:</div>
                            @:<div class="found-tour">
                        }
                            <h3>От @Html.DisplayFor(m => c.Cost)&nbsp;@Html.DisplayFor(m=>c.Valuta)</h3><br />
                            <a href='@Url.Action("Index", "TourDisplay", new {id = c.TourId})'><img class="tourImg" style="max-height: 150px; max-width: 250px" src="@Html.DisplayFor(m => c.TourImg)"></a>
                            <a class="titleTour" href='@Url.Action("Index", "TourDisplay", new {id = c.TourId})'> @Html.DisplayFor(m => c.NameTour)</a>
                            <div class="date-select mini">
                                <label style="margin-left: -23px;">
                                    <select id="selectDate">
                                        @foreach (var item in c.DateTour)
                                        {
                                            <option>
                                                @Html.DisplayFor(m => item.FirstDate) - @Html.DisplayFor(m => item.SecondDate)
                                            </option>
                                        }
                                    </select>
                                </label>
                            </div><br/>
                     index++;
                     }
                </div>
            </div>
        </form>
    </div>
</div>
<script>
    function TourSearch()
    {
        if ($('#bar').width() <= 1100) {
            $('#filter').show();
            $('.layout-left-column').css({ 'float': 'auto','min-width':'215px','max-width':'215px', 'width': '70%','margin-left':'-100%','top': '104px','position':'fixed','z-index':'4'});
            $('.layout-main-right').css({ 'margin-left': '3%', 'width': '100%', 'margin-top': '20px' });
            $('.tourImg').css({ 'max-width': '100%', 'max-height': '100%' });
            $('.found-tour').css({ 'width': 'auto', 'margin-top': '20px' });
            $('.date-select label').addClass('hide');
            $('.date-select.mini select').css({ 'font-size': '14px !important', 'text-decoration': 'underline' });
            $('#selectDate').css('font-size', '14px !important');
            $('.forHide').hide();
            $('#Prices').css({ 'margin-bottom': '17px' });
        }
        else {
            $('#filter').hide();
            $('.forHide').show();
            $('.layout-left-column').css({ 'float': 'left','min-width':'auto','max-width':'auto','width': '30%', 'margin-left': '0px !important', 'position': 'inherit'});
            $('.layout-main-right').css({ 'margin-left': '33%', 'width': '67%','margin-top':'0px' });
            $('.tourImg').css({ 'max-width': '250px', 'max-height': '150px' });
            $('.found-tour').css({ 'width': '250px', 'margin-top': '-38px' });
            $('.date-select label').removeClass('hide');
            $('.date-select.mini select').css({ 'font-size': '1em', 'text-decoration': 'none' });
            $('#selectDate').css('font-size', '1em');
            $('#Prices').css({ 'margin-bottom': '0px' });
        }
    }

    $(function ()
    {
            TourSearch();

            $('#filter').click(function () {
                if (!$('.layout-left-column').hasClass('open')) {
                     $('#filter').css('left', '172.6px');
                }
                else {
                    $('#filter').css('left', '-42px');
                }
                $('.layout-left-column').toggleClass('open');
                $('.layout-left-column').css('transition','0.5s');
            });

            $(window).resize(function(){
                TourSearch();
            });

        });
</script>

WorkWithKOTE/Views/TourSearch/SearchResult.cshtml
@model IEnumerable<WorkWithKOTE.Models.Tour>
@using WorkWithKOTE.Code

<style>
    .transportSelect input[type=checkbox]{
        display: inline;
    }
</style>

<div class="searchForm">
    
    <input type="text" name="Places" placeholder="Куда"/>
    @Html.DropDownList("PlaceDepartmen", DropDown.PlaceDeparture(), "Город выезда")

    @if (ViewBag.Counter == 0)
    {
       @* <label> Возвращения</label>
        <input type="date" name="DateSecond"/>*@

        <div> Тип транспорта
            <div class="transportSelect">
                @Html.CheckBox("IsBus") <label for="IsBus">Автобус</label><br/>
                @Html.CheckBox("IsShip") <label for="IsShip">Лайнер</label><br/>
                @Html.CheckBox("IsTrain") <label for="IsTrain">Поезд</label><br/>
                @Html.CheckBox("IsAriplane") <label for="IsAriplane">Самолет</label>
            </div>
        </div>

        foreach (var item in DropDown.Tags())
        {
            if (!String.IsNullOrEmpty(item.Text))
            {
                <input type="checkbox" name="Tags" value="@item.Text"/>
                <label>@item.Text</label>
            }
        }
    }

    @if (ViewBag.Counter == 1)
    {
       @* <label> Возвращения</label> <input type="date" name="DateSecond" /> *@

        if (Model.Any())
        {
            <div> Тип транспорта
                <div class="transportSelect">
                    @foreach (var item in Model)
                    {
                        int B = 0;
                        int S = 0;
                        int T = 0;
                        int A = 0;

                        if (item.IsBus && B == 0)
                        {
                            @Html.CheckBox("IsBus")
                            <label>Автобус</label>
                            B++;
                        }

                        if (item.IsShip && S == 0)
                        {
                            @Html.CheckBox("IsShip")
                            <label>Лайнер</label>
                            S++;
                        }

                        if (item.IsTrain && T == 0)
                        {
                            @Html.CheckBox("IsTrain")
                            <label>Поезд</label>
                            T++;
                        }

                        if (item.IsAriplane && A == 0)
                        {
                            @Html.CheckBox("IsAriplane")
                            <label>Самолет</label>
                            A++;
                        }

                    }
                </div>
            </div>
            foreach (var item in Model)
            {
                foreach (var items in item.Tag)
                {
                    if (!String.IsNullOrEmpty(items.TagName))
                    {
                        <input type="checkbox" name="Tags" value="@items.TagName"/>
                        <label>@items.TagName</label>
                    }
                }
            }

            if (ViewBag.PlaceDeparture != null)
            {
                <select name="PlaceDepartmen">
                    <option selected>Город выезда</option>
                    @foreach (var item in ViewBag.PlaceDeparture)
                    {
                        <option>@item</option>
                    }
                </select>
            }
        }
    }

    <input type="date" name="DateFirst"/>
    <input type="date" name="DateSecond"/>
    <input type="text" name="MinValue" value="1000"/>
    <input type="text" name="MaxValue" value="3000"/>

    <input type="submit" value="Искать"/>
</div>

<div id="target2">
    @foreach (var c in Model)
        {
        <h3>От @Html.DisplayFor(m => c.Cost)&nbsp;@Html.DisplayFor(m => c.Valuta)</h3><br />
        <a href='@Url.Action("Index", "TourDisplay", new {id = c.TourId})'><img class="tourImg" style="max-height: 150px; max-width: 250px" src="@Html.DisplayFor(m => c.TourImg)"></a>
        <a class="titleTour" href='@Url.Action("Index", "TourDisplay", new {id = c.TourId})'> @Html.DisplayFor(m => c.NameTour)</a>
        <div class="date-select mini">
            <label style="margin-left: -23px;">
                <select id="selectDate">
                    @foreach (var item in c.DateTour)
                        {
                        <option>
                            @Html.DisplayFor(m => item.FirstDate) - @Html.DisplayFor(m => item.SecondDate)
                        </option>
                        }
                    </select>
                </label>
            </div>
        }
</div>